#!/usr/bin/env python3
"""Bootstrap a new Python project.

Creates the directory structure, a virtualenv with dev dependencies, ruff
linting config, a git repo with a pre-commit lint hook, and env files.

Usage:
    python3 environment_bootstrap.py <path> [--name PKG] [--force] [--skip-install]

Uses only the Python standard library.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

GITIGNORE = """\
__pycache__/
*.py[cod]
.venv/
.env
.ruff_cache/
.pytest_cache/
*.egg-info/
dist/
build/
"""

ENV_EXAMPLE = """\
# Copy to .env and fill in real values. .env is git-ignored.
APP_ENV=development
# SECRET_KEY=
"""

PYPROJECT = """\
[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.11"

[tool.ruff]
line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
"""


def build_files(name):
    pkg = name.replace("-", "_").replace(" ", "_").lower()
    return {
        ".gitignore": GITIGNORE,
        ".env.example": ENV_EXAMPLE,
        "pyproject.toml": PYPROJECT.format(name=name),
        "requirements.txt": "# Runtime dependencies\n",
        "requirements-dev.txt": "ruff\npytest\n",
        "README.md": f"# {name}\n\nBootstrapped project.\n",
        f"{pkg}/__init__.py": '__version__ = "0.1.0"\n',
        "tests/test_smoke.py": "def test_smoke():\n    assert True\n",
    }


HOOK = """\
#!/bin/sh
# Auto-generated by environment_bootstrap: lint staged code before each commit.
if [ -x .venv/bin/ruff ]; then RUFF=.venv/bin/ruff; else RUFF=ruff; fi
exec "$RUFF" check .
"""


def venv_bin(target, exe):
    sub = "Scripts" if os.name == "nt" else "bin"
    return str(target / ".venv" / sub / exe)


def run(cmd, cwd):
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, cwd=cwd).returncode


def main():
    p = argparse.ArgumentParser(description="Bootstrap a new Python project.")
    p.add_argument("path", help="Target project directory.")
    p.add_argument("--name", help="Package name (default: directory name).")
    p.add_argument(
        "--force", action="store_true", help="Allow bootstrapping into a non-empty directory."
    )
    p.add_argument(
        "--skip-install",
        action="store_true",
        help="Create the venv but skip 'pip install' of dev deps.",
    )
    args = p.parse_args()

    target = Path(args.path).expanduser().resolve()
    name = args.name or target.name
    if target.exists() and any(target.iterdir()) and not args.force:
        sys.exit(f"error: {target} is not empty (use --force to override)")

    print(f"Bootstrapping '{name}' in {target}\n")

    print("Writing project files:")
    for rel, content in build_files(name).items():
        f = target / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content)
        print(f"  + {rel}")

    print("\nSetting up git + venv:")
    if not (target / ".git").exists():
        run(["git", "init", "-q"], target)
    run([sys.executable, "-m", "venv", ".venv"], target)

    if not args.skip_install:
        if (
            run([venv_bin(target, "pip"), "install", "-q", "-r", "requirements-dev.txt"], target)
            != 0
        ):
            print("  ! dev dependency install failed (install later manually)")

    hook = target / ".git" / "hooks" / "pre-commit"
    hook.write_text(HOOK)
    hook.chmod(0o755)
    print("  + .git/hooks/pre-commit (runs ruff)")

    env = target / ".env"
    if not env.exists():
        env.write_text((target / ".env.example").read_text())
        print("  + .env (from .env.example)")

    print(f"\nDone. Next:\n  cd {target}\n  source .venv/bin/activate")


if __name__ == "__main__":
    main()
